#' @title Export Virusparies Plots
#'
#' @description This function allows the user to export plots in different formats.
#'
#' @details export plots generated by functions within the Virusparies package.
#'
#' @param plot_object A graphical object to be exported.
#' @param file_name Name of the output file. Default is "plot.png".
#' @param width The width of the output file. Default is 800 pixels.
#' @param height The height of the output file. Default is 600 pixels.
#' @param units The units of the width and height parameters. Can be one of "in", "cm", "mm", or "px". Default is "px".
#' @param pointsize The point size of the font. Default is 12.
#'
#' @examples
#' path <- system.file("extdata", "virushunter.tsv", package = "Virusparies")
#' vh_file <- importVirusTable(path)
#'
#' @import grDevices
#' @export
exportVirusPlot <- function(plot_object,
                            file_name = "plot.png",
                            width = 800,
                            height = 600,
                            units = "px",
                            pointsize = 12) {
  format <- sub('.*\\.', '', tolower(file_name))
  print(paste0(file_name," will be exported in the following format: ",width,"X",height," in ",format," format."))
  if (format %in% c("png", "jpeg", "pdf", "svg")) {
    if (format == "png") {
      png(filename = file_name, width = width, height = height, units = units, pointsize = pointsize)
    } else if (format == "jpeg") {
      jpeg(filename = file_name, width = width, height = height, units = units, pointsize = pointsize)
    } else if (format == "pdf") {
      pdf(file = file_name, width = width, height = height, pointsize = pointsize)
    } else if (format == "svg") {
      svg(filename = file_name, width = width, height = height, pointsize = pointsize)
    }
    print(plot_object)
    dev.off()
  } else {
    stop("Unsupported file format. Supported formats are 'png', 'jpeg', 'pdf', and 'svg'.")
  }
}
