#' @title Export Virusparies Plots
#'
#' @description This function allows the user to export plots in different formats.
#'
#' @details export plots generated by functions within the Virusparies package.
#'
#' @param file_name Name of the output file.
#' @param plot The plot to be exported.
#' @param device The device used for output.
#' Can be one of "eps", "ps", "tex", "pdf", "jpeg", "tiff", "png", "bmp", "svg", or "wmf" (windows only).
#' If NULL (default), the device is guessed based on the filename extension.
#' @param path The directory where the plot will be saved. Default is NULL (working directory).
#' @param scale A scaling factor. Default is 1.
#' @param width The width of the output file. Default is 800 pixels.
#' @param height The height of the output file. Default is 600 pixels.
#' @param units The units of the width and height parameters.
#' Can be one of "in", "cm", "mm", or "px". Default is "px".
#' @param dpi The resolution of the output device in dots per inch. Default is 300.
#' @param limitsize Whether to limit the size of the output file to the dimensions of the plot. Default is TRUE.
#' @param bg The background color of the plot. Default is NULL.
#' @param create.dir Whether to create the directory specified in the path if it does not exist. Default is FALSE.
#' @param ... Additional arguments passed to.
#'
#' @details
#' This function exports plots in various formats supported by Virusparies.
#' Supported devices include "eps", "ps", "tex", "pdf", "jpeg", "tiff", "png", "bmp", "svg", or "wmf" (Windows only).
#' When 'device' is set to NULL, the file extension in 'filename' is used to determine the device.
#'
#' Depending on the plot, the final image might be cropped or truncated.
#' We recommend experimenting with height, width, and resolution.
#'
#' The default theme for every plot is "minimal," resulting in a transparent plot.
#' If you want to avoid transparent plots, please change the theme accordingly.
#'
#'
#'
#'
#' @return a message indicating that export was successful.
#'
#' @author Sergej Ruff
#' @examples
#' path <- system.file("extdata", "virushunter.tsv", package = "Virusparies")
#' vh_file <- importVirusTable(path)
#'
#' # Basic plot
#' plot <- VhgIdentityScatterPlot(vh_file,cutoff = 1e-5)
#'
#' \dontrun{
#'
#' # first export
#' exportVirusPlot(plot=plot,file_name="testplot.png",width=8,height=6,units="in")
#'
#' # second export with device argument
#' exportVirusPlot(plot=plot,file_name="testplot",width=8,height=6,units="in",device = "png")
#'
#' }
#'
#' @seealso
#' VirusHunterGatherer is available here: \url{https://github.com/lauberlab/VirusHunterGatherer}.
#'
#' @importFrom ggplot2 ggsave
#' @export
exportVirusPlot <- function(
                            file_name,
                            plot = NULL,
                            device = NULL,
                            path = NULL,
                            scale = 1,
                            width = NA,
                            height = NA,
                            units = c("in", "cm", "mm", "px"),
                            dpi = 300,
                            limitsize = TRUE,
                            bg = NULL,
                            create.dir = FALSE,
                            ...) {
  format <- sub('.*\\.', '', tolower(file_name))

  if (!is.null(device) && !(device %in% c("eps", "ps", "tex", "pdf", "jpeg", "tiff", "png", "bmp", "svg", "wmf"))) {
    stop("Unsupported device. Supported devices are 'eps', 'ps', 'tex', 'pdf', 'jpeg', 'tiff', 'png', 'bmp', 'svg', and 'wmf'.")
  }

  if (is.null(device)) {
    device <- ifelse(format %in% c("eps", "ps", "tex", "pdf", "jpeg", "tiff", "png", "bmp", "svg", "wmf"), format, stop("Unsupported file format or device. Supported formats are 'eps', 'ps', 'tex', 'pdf', 'jpeg', 'tiff', 'png', 'bmp', 'svg', and 'wmf'."))
  }

  message(paste0(file_name, " will be exported in the following format: ", width, "X", height, " using ", device, " device."))

  ggsave(filename = file_name,
         plot = plot,
         device = device,
         path = path,
         scale = scale,
         width = width,
         height = height,
         units = units,
         dpi = dpi,
         limitsize = limitsize,
         bg = bg,
         create.dir = create.dir,
         ...)

  message("Plot export completed successfully.")
}
